### ISSUE TITLE
templates\fart.exe is missed in template

### ISSUE THREAD

**Issue by JasperGuo** [soumikmohianuta/pixtoapp#2]
Dear authors,

Great thanks for your efforts on the project. 
When I try to setup the project, everything works well except that the fart.exe is missed in the template folder.

Would you mind to upload it ?

Best Regards,
Jasper

**Comment by JasperGuo** [comment]
Well, I finally find that the project can work well without these `fart.exe`.

**Comment by w4lle** [comment]
Yes,I found it too.
fart.exe is a shell util, it has nothing effect with missing.
Thanks author for this project.
