### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by sbunian** [soumikmohianuta/pixtoapp#4]
Hi, Is this the official code implementation of the REMAUI paper

**Comment by csallner** [comment]
The REMAUI implementation that was evaluated in the ASE 2015 REMAUI paper (http://ranger.uta.edu/~csallner/papers/nguyen15reverse.pdf) was in Java. This repository contains @soumikmohianuta's re-implementation in Python, which also powers our publicly hosted REMAUI version (currently at http://pixeltoapp.com/). The Python version does not contain all the features of the original Java version. But we hope it can still be useful, either as a starting point for others or as a baseline for evaluations.

**Comment by yzy-gary** [comment]
Hi, where can we obtain the java version of REMAUI
